### ISSUE TITLE
Servers panel stealing focus

### ISSUE THREAD

**Issue by gaspo100** [redhat-developer/vscode-rsp-ui#245]
Not sure if this is the same issue as #156 or a new one but the focus stealing has not been completely resolved in the latest VS Code (1.70.2) and the Community Server Connector (0.23.13).

I have the "showChannelOnServerOutput" unchecked, the Output window does not focus but instead the Servers panel now focuses on itself whenever I save the file or perform other actions in the VS Code UI.
![image](https://user-images.githubusercontent.com/931540/187140839-d648b790-38a1-4b4a-a3ec-8a25f040c729.png)
![image](https://github.com/redhat-developer/vscode-rsp-ui/assets/931540/e29831a0-35db-4c85-ba50-867aff8b54a7)

**Comment by fb-datax** [comment]
I can confirm the behavior and it is annoying, Any progress on this?

**Comment by robstryker** [comment]
I haven't been able to replicate this at all.  :|  

Does it happen all the time? Or only if an RSP is started? Or only if a server is started as well (wfly, tomcat, etc)?  or only if a server is started AND the given file is currently deployed? 

Trying to figure out the limits of what you're experiencing.

**Comment by gaspo100** [comment]
Yes it only happens when the RSP is started and the Tomcat is running. (I had the wrong image in my my original post showing Tomcat was stopped, updated now).

So, while Tomcat is running I make changes to some files in the editor then I press Ctrl+S to save the file and the editor loses focus to Servers pane (due to publishing the changed file?). You need to then click again on to editor to continue typing.

Even more annoying is when I press Ctrl+Shift+F to search within the files, then in the middle of typing the search criteria or reviewing the results the Search panel is replaced with the Explorer having the Servers focused.

**Comment by jakopo87** [comment]
It happens when a publish action is performed, even if there is nothing to deploy, or when a new server is installed.

Steps to reproduce:
- Open VS Code;
- Open a file or an empty editor tab (ensure is focused);
- Install a server;
- At the end of the installation, the focus changes from the editor tab to the new server node;
- Put the focus back on the editor tab;
- Execute "Publish Server" from the command palette (Full or Incremental);
- The focus changes from the editor tab to the server node;

Both are caused by [this line](https://github.com/redhat-developer/vscode-rsp-ui/blob/678add39ac81ee3a891c964b9afdccaab0968e03/src/serverExplorer.ts#L234) in the `selectNode()` function, changing to `focus: false` resolves the issue.

**Comment by robstryker** [comment]
Good find. I'll likely change it to pull from the setting regarding console out, changing the setting to be to take focus on console out or changes to the view. 

But really good find.

**Comment by gaspo100** [comment]
@jakopo87 Thanks for the find.
I have modified installed instance of redhat.vscode-rsp-ui and can confirm that setting focus: false in the above file will solve this issue.  
I'll run this until the official fix comes through.

**Comment by robstryker** [comment]
Sorry for delay. I've been busy with other work.  I've opened https://github.com/redhat-developer/vscode-rsp-ui/pull/289  with your suggested patch and not the more in depth one of respecting the setting. I just can't see any reason we should steal focus even with the setting enabled.
