### ISSUE TITLE
Downloading server: Change accepting license options to Yes - No

### ISSUE THREAD

**Issue by odockal** [redhat-developer/vscode-rsp-ui#29]
Or maybe Yes, I agree / No, I disagree or similar.

**Comment by odockal** [comment]
I do not like True / False option...

**Comment by robstryker** [comment]
@odockal  The problem here is that the UI has absolutely no idea what question is being asked. The server could be asking "Please set the boolean value of rsp.internal.setting:  true/false"  

Basically, the server sends a list of questions / properties that need to be filled out, along with their type (List, Map, String, int, boolean, etc).  The UI has absolutely no idea what the text of those messages may be. All it knows is that the answer must be a boolean. And, any choice it makes here (in terms of yes/no or true/false) must apply to ALL boolean questions from ALL rsps.  

So... would you prefer the answer to all questions that are boolean be true/false? Or would you prefer the question to ALL questions that are boolean be yes/no ?  Clearly there's no right answer here.

**Comment by jrichter1** [comment]
@robstryker except the quick pick options are defined purely in the UI
https://github.com/redhat-developer/vscode-rsp-ui/blob/master/src/extensionApi.ts#L491

**Comment by lstocchi** [comment]
@jrichter1 I think you misunderstood Rob. The quickpick options are defined in the UI for sure and can be easily changed. The problem here is that this method is inside a for which loops over items returned by the rsp-server ( https://github.com/redhat-developer/vscode-rsp-ui/blob/master/src/extensionApi.ts#L392 ). 

If the item response type is a boolean, those options (True, False) are always displayed but the UI doesn't know the content of the message which is going to be displayed so it cannot know if Yes/No is better than True/False. So if we change the options to Yes/No they will always be displayed if the server sends us a message of type bool.

And what happens if we have a question like "Please set the boolean value of rsp.internal.setting: true/false"? In this case True/False will be a better choice.

Maybe we can do a mix? (Yes/True, No/False)? wdyt? @odockal

**Comment by odockal** [comment]
@lstocchi Mix is alright then..
