### ISSUE TITLE
Error trying to save server properties

### ISSUE THREAD

**Issue by lampsbr** [redhat-developer/vscode-rsp-ui#45]
I'm trying to edit a property in my wildfly 12 server. 

- I right click it and select **Edit Server**
- a **.json** file shows up in my editor
- I add a string to my **vm.args.orverride.string** (-XXaltjvm=dcevm -javaagent:/c:/mydir/hotswap-agent-1.3.1-SNAPSHOT.jar)
- I try to save it using ctrl + S

In this moment I get the following error message:
Unable to save server properties - server id is invalid
Source: Remote Server Protocol UI (extension)

What am I doing wrong?

**Comment by lstocchi** [comment]
Which OS are you using? Windows 10?

**Comment by lstocchi** [comment]
I was able to reproduce the error. Looking at that right now.

**Comment by lstocchi** [comment]
@lampsbr thanks for reporting this bug. The error should now be fixed #46 . 

Could you please try and see if you still face any error? 
To test this fix you can create your own vsix file (and install it on vscode) by using this branch (https://github.com/lstocchi/vscode-rsp-ui/tree/issue45I) or directly download the one created by me (https://github.com/lstocchi/vscode-rsp-ui/pull/1/files).

Let me know if you have any problem. Thank you.

**Comment by lampsbr** [comment]
Yes, I'm using windows 10. I'll try to install the vsix file and I'll reply again asap.

**Comment by lampsbr** [comment]
Downloaded and installed the vsix. Everything working fine. Thank you very much!

**Comment by lstocchi** [comment]
@lampsbr i just tried it on linux and it seems working (at least i'm able to find some hotswap agent messages in the console), i'll try it on windows soon. 

Before to proceed maybe i have an idea why it's failing for you. Before saving the settings do you set the flag "args.override.boolean" to true? This is required by the server otherwise it will overwrite all your changes. 

Unfortunately we really have bad documentation on this plugin and i promise you we are going to improve it soon. In the meantime you can read more about this setting here https://github.com/redhat-developer/rsp-server/pull/423

**Comment by lampsbr** [comment]
@lstocchi thanks for the feedback! I'll try it tomorrow morning and update this issue. =)

**Comment by lampsbr** [comment]
Hi, sorry for taking so long to try it. Everything worked fine after changing args.override.boolean to true.

**Comment by adietish** [comment]
Issue was identified: in order to be able to change values one has to set "args.override.boolean" to true.
We'd really need to document this.
Resolving.
