### ISSUE TITLE
Write some documentation for this extension

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/vscode-rsp-ui#47]
Currently there is no documentation related to this extension and many users are lost because don't know how to use some of the functionalities available. We should update what we have and/or write some blog post and/or create a Q/A section.

**Comment by lstocchi** [comment]
README updated in both vscode-rsp-ui and vscode-server-connector extension. Closing it.

- https://github.com/redhat-developer/vscode-rsp-ui/commit/324297429a6ad7f450726af0420b1195b7bb167a
- https://github.com/redhat-developer/vscode-server-connector/commit/f343f8fd49cd0c0c4d4a760802ef92176525b0e9

**Comment by pedrobbarbosa** [comment]
I'm still missing some configurations that need to be set in the json file. 
There's no much information about it.  I'm getting `12:00:19,551 INFO  [ServerImpl] Bootstrap URL: null` and was not able to find in the repo how to change that in the `settings.json` file.
Is there something that im missing?

**Comment by robstryker** [comment]
That sounds like a bug and should be opened in its own issue. 

Also, this is unlikely to be fixed via a change to `settings.json` but rather by right-clicking a given server and clicking `Edit Server`.  The rsp-ui tools do not have many global settings that would be fixed in `settings.json` other than what VM to use when launching the RSP. All problems with a specific server (tomcat x.y.z, wildfly x.y.z, etc) would be fixed in that server's configuration file, not the global settings.

**Comment by robstryker** [comment]
It's also worth noting that bugs like this should be placed in the correct repository. Any bug with starting / stopping / deploying to / interacting with a wildfly or eap server should be placed in the rsp-server github repository issues section.  Any bug with tomcat, felix, karaf, etc, should be placed in the rsp-server-community repository.

**Comment by pedrobbarbosa** [comment]
I have passed the params i wanted inside the `args.vm.override.string` and it's working now.
The `Patch URL: null` and `Bootstrap URL: null` still giving me null, even when the project is running as expected.
I am not certanly if it's a bug or something that im doing wrong, so i will not open any issue for now.
Thanks for the reply, @robstryker .
