### ISSUE TITLE
Create new server: cannot via ctx menu, can only via toolbar button

### ISSUE THREAD

**Issue by adietish** [redhat-developer/vscode-rsp-ui#49]
I would expect a context menu entry where I can create a new server. If I right click into the servers view into the empty area, there's no context menu. I'd expect something like "Create new server" to be available.
Currently the only option is via toolbar item "Create new Server...".

**Comment by lstocchi** [comment]
Currently there are 3 ways to create a new server: 1) quickpick 2) ctx menu - when right clicking on a rsp node 3) by clicking on the button on the top right of the servers section.

I removed the action when right clicking in the empty area because now the first level consists of rsp providers and i would expect that the commands in this ctx menu are related to this first level (so i would expect "create new rsp providers" or something like that). But, thinking about it, if we have the button in the top right of the section we could also add the action in the ctx menu when right clicking in an empty area.

**Comment by adietish** [comment]
@lstocchi ok, explanation about motivations makes sense. But yes, if there's  action in the toolbar I don't see why the very same command couldn't be launched from the ctx menu. Good UX advice would suggest to have multiple ways to achieve the same thing.

**Comment by robstryker** [comment]
+1 on having action on empty selection. They may need to select a running rsp as the first step, but that's fine.

**Comment by lstocchi** [comment]
I don't know if it's me but the ctx menu doesn't appear anymore if i click on an empty space. Is it happening to you too? I tried multiple things without any success.
I'm using VScode version 1.37.1

**Comment by lstocchi** [comment]
Closing it as vscode doesn't support the click on the empty space anymore. If you find a way to make it work feel free to reopen it.
