### ISSUE TITLE
Autopublisher does not kick in if server is not running

### ISSUE THREAD

**Issue by adietish** [redhat-developer/vscode-rsp-ui#51]
steps:

1. EXEC: create new wildfly 17 server
1. EXEC: add new exploded war for kitchensink (kitchensink/target/kitchensink)
1. ASSERT: server changes state to "(Full Publish Required)"
1. EXEC: wait for Autopulisher to kick in

Result:
Nothing happens, Autopublisher never kicks in

Expected result:
Autopublisher should publish the new deployment

in contrast Autopublisher kicks in if the server is running.

**Comment by robstryker** [comment]
I do not believe auto-publisher should be kicked if server is stopped. WTP doesn't auto-publish to stopped servers. That's not a sufficient reason not to do it here, but, it feels strange to me to autopublish to stopped servers.

**Comment by adietish** [comment]
We allow manual publishing if the server is stopped. Why would be limit the autopublisher to a running server? Feels inconsistent.

**Comment by robstryker** [comment]
I'm going to reject this issue for a few reasons. 

First, the bug is with rsp-server. The auto-publisher is part of the rsp, and not part of the UI at all. 

Second, the purpose of auto-publishing is to see your changes live on the server. When the server is stopped, that purpose is defeated. 

Third, if I remember correctly (I'm like 85% sure?) eclipse wtp functions the same way.
