### ISSUE TITLE
no full publish executed if server has orphaned deployment

### ISSUE THREAD

**Issue by adietish** [redhat-developer/vscode-rsp-ui#52]
I faced the following when I used the same server runtimes in Eclipse, too, where I added/removed deployments. Once back in vscode I got stuck with servers that I could not get rid of orphaned deployments (that I had tampered with in Eclipse)

steps:
1. ASSERT: have wildfly 17.0.1 server running
1. EXEC: add (exploded) kitchensink deployment to it
1. ASSERT: have the deployment published (automatic publishing kicks in and does it for you)
1. EXEC: remove the kitchensink.war folder in <server>/standalone/deployments
1. ASSERT: wait until the server undeploys kitchensink.war
1. ASSERT: server turns to "(Full Publish Required)"
1. EXEC: pick "Publish Server (Full)" in the context menu

Result:
Nothing happens.

**Comment by lstocchi** [comment]
I was trying to replicate it but i have a different behavior.

steps:

ASSERT: have wildfly 17.0.1 server running
EXEC: add (exploded) kitchensink deployment to it
ASSERT: have the deployment published (automatic publishing kicks in and does it for you)
EXEC: remove the kitchensink.war folder in /standalone/deployments
ASSERT: in the log i can find this warning "[org.jboss.as.server.deployment.scanner] (DeploymentScanner-threads - 2) WFLYDS0007: The deployment scanner found that the content for exploded deployment kitchensink.war has been deleted, but auto-deploy/undeploy for exploded deployments is not enabled and the kitchensink.war.deployed marker file for this deployment has not been removed. As a result, the deployment is not being undeployed, but resources needed by the deployment may have been deleted and application errors may occur. Deleting the kitchensink.war.deployed marker file to trigger undeploy is recommended." and the server remains to (Synchronized). Nothing happens. If i publish it again a new kitchensink.war folder is created.

**Comment by lstocchi** [comment]
If i do the same thing with a file deployment, the behavior is different

steps:

1. ASSERT: have wildfly 17.0.1 server running
2. EXEC: add (file) jboss-as-kitchensink.war deployment to it
3. ASSERT: have the deployment published (automatic publishing kicks in and does it for you)
4. EXEC: remove the jboss-as-kitchensink.war file in /standalone/deployments
5. ASSERT: i can see it was undeployed "jboss-as-kitchensink.war.undeployed"
6. ASSERT: server still is "(Synchronized)"

**Comment by robstryker** [comment]
Synchronization is a one-way relationship. We only watch changes in the project / source folder. We do not "watch" the destination folder. If you go muck up stuff in the destination folder, we will not notice. Also, this will not (and should not) be changed. Watching both source and destination folders for changes is a bad idea. 

In JBossTools / devstudio / crs, the same is true. If you go and modify the destination folder, the servers view will not switch to 'unsynchronized' or otherwise recognize your changes. The tooling is only listening to your source folder and for changes in the source folder to be copied to the destination. It responds to deltas in the source (file added, file changed, file deleted, etc) and never once actually compares to the destination. 

Closing as wont-fix.
