### ISSUE TITLE
Missing stopping log from the server on the console output channel

### ISSUE THREAD

**Issue by odockal** [redhat-developer/vscode-rsp-ui#66]
1. Create some server (wf 18)
2. Start the server
3 ASSERT: Server is started and output channel (output) show server output log
4. Stop the server
5. ASSERT: Output channel show server stopping
Actual: It does nothing, there is only previous log preserved in output channel

**Comment by robstryker** [comment]
This should have been fixed by https://github.com/redhat-developer/vscode-rsp-ui/commit/6b71d4521034887cd7acb376a9854e5aa059673e

vscode-rsp-ui was using 'true' for the 'force' flag all the time, so rsp-server was simply terminating the process (and so no output).  But this was fixed a month ago, which kinda indicates however you're testing this isn't correct because I'm not able to replicate this bug anymore.

**Comment by odockal** [comment]
I updated the extension and run locally, now properly because the issue is gone as you explained. So closing this. Thanks
