### ISSUE TITLE
Allow users to start server with custom sh script

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/vscode-rsp-ui#89]
A user requested to being able to start his wildfly server by using a custom standalone.sh script. Any way we can do it?

**Comment by robstryker** [comment]
Our wildfly / eap / jboss launches are java specific. But the .sh and .bat scripts really just customize the launch args for the java command, so they should be able to configure most of what they'd want to customize via the program and vm args, no?

**Comment by robstryker** [comment]
Where was a user requesting this? Email? Gitter? Can we paste their comments directly?

**Comment by lstocchi** [comment]
On Gitter, "I'm running a very customized wildfly install with custom standalone.sh and standalone.xml" ... after finding out that there is a flag to make wildfly instance uses a specific standalone.xml file, he asks "is there a similar property for the standalone.sh?"

**Comment by robstryker** [comment]
Excerpt from gitter:

Hi @Traufvihal, you can use the flag "wildfly.server.config.file". Just make sure that the new standalone file is stored in the same folder as the default one. Right click on the wildfly instance you want to edit -> Edit server -> add "wildfly.server.config.file": "yournewstandalone.xml"

@Traufvihal Hey, so there's more options for you too. You can change the config file, but you can also change hte program args and vm args being passed into the java launch
@Traufvihal you can set property "args.override.boolean" to true and then "vm.args.override.string" and "program.args.override.string" can be customized
@Traufvihal Since wildfly's .bat and .sh scripts are basically jsut entry points to the java command, this should give you all the control you need.

**Comment by robstryker** [comment]
Seems to have been resolved.
